services:
  item-app:
    image: yufebra/item-app:v1
    depends_on:
      - item-db
    ports:
      - "80:8080"
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    ports:
      - "27017:27017"

volumes:
  app-db:
    driver: local